#########################
### Nome da aplicacao ###
#########################
spring.application.name=catalogo

######################################################################
### Configuracao do Console H2 (Acesse: localhost:8080/h2-console) ###
######################################################################
#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console
#spring.datasource.url=jdbc:h2:mem:catalogodb
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=

######################################################################
###              Configuracao do PostgreSQL                        ###
######################################################################
# Configuracoes de Conexao
spring.datasource.url=jdbc:postgresql://localhost:5432/catalogo_db
spring.datasource.username=admin
spring.datasource.password=admin

# Configuracoes do Hibernate/JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
